#!/usr/bin/env lua5.4
---@version 5.4
-- /qompassai/hyprland/hypr.d/exec/apps.lua
-- Qompass AI Hyprland 0.55+ Executable Apps Lua Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- ###################################################
local M = {}
M.app_drawer = 'hyprlauncher'
M.bar = 'waybar'
M.blue = 'termshark'
M.blue2 = 'wireshark'
M.bt = 'bluetui'
M.bt2 = 'blueman-manager'
M.calendar = 'khal interactive'
M.cite = 'Zotero'
M.color_picker = 'hyprpicker'
M.clipboard = 'wl-copy'
M.dis = 'vesktop'
M.dis2 = 'discordo'
M.editor = 'nvim'
M.emoji = 'hypremoji'
M.entry_background_color = 'rgba(41000311)'
M.entry_border_color = 'rgba(896E6C55)'
M.entry_color = 'rgba(FFDAD6FF)'
M.font_family = 'DaddyTimeMono Nerd Font Mono'
M.font_family_clock = 'DaddyTimeMono Nerd Font Mono'
M.font_material_symbols = 'Material Symbols Rounded'
M.hyprpaper = 'hyprpaper'
M.launcher = 'hyprlauncher'
M.lock = 'hyprlock'
M.logout = 'hyprctl dispatch exit'
M.files = 'dolphin'
M.menu = 'fuzzel --dmenu'
M.tele = 'ithil'
M.tele2 = 'Telegram'
M.term = 'foot'
M.music = 'ncspot'
M.network = 'nmtui'
M.notify = 'makoctl'
M.notify_action_menu = [[makoctl menu wofi -d -p 'Choose Action: ']]
M.notify_default = 'makoctl mode -s default'
M.pass_man = 'pass'
M.password_menu = 'pass | fuzzel --dmenu | xargs pass show'
M.pdf = 'Zathura'
M.record = 'obs'
M.record2 = 'audacity'
M.stats = 'btop'
M.screen_share = 'xdg-desktop-portal-hyprland'
M.screenshot = 'hyprshot -m region'
M.text_color = 'rgba(FFDAD6FF)'
M.term = 'ghostty'
M.term2 = 'foot'
M.update = 'pkcon update'
M.usb = 'usbview'
M.voice = 'hyprvoice'
M.vol_ctrl = 'wiremix'
M.vol_ctrl2 = 'hyprpwcenter'
M.vol_down = 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
M.vol_mute = 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
M.volume_up = 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+'
M.wp = 'hyprpaper'
M.weather = 'wttr.in'
M.web = 'firefox'
M.web2 = 'google-chrome-canary'
M.window_switcher = 'bemenu-run --window-mode'
return M
