# /qompassai/hyprland/hyprtoolkit.conf
# Qompass AI Hyprland HyprToolkit Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
#accent = FF00FFCC
#alternate_base = FF272727
accent           = 0xFF00FFCC
accent_secondary = 0xFF0099F0
background       = 0xFF181818
base             = 0xFF202020
bright_text      = 0xFFFFDEDE
h1_size          = 19
h2_size          = 15
h3_size          = 13
font_size        = 11
icon_theme       = Flat-Remix-Red-Dark
small_font_size  = 10
text             = 0xFFDADADA
