## /qompassai/hyprland/hypr/rustrland.toml
# Qompass AI Hyprland Rustrland Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
[pyprland]
plugins = [
    "scratchpads",
     "magnify",
     "expose", 
     "workspaces_follow_focus",
]
[pyprland.variables]
term_classed = "kitty --class"
[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
restore_focus = true
position = "12.5% 20%"
[scratchpads.filemanager]
animation = "fromRight"
command = "thunar"
class = "thunar"
size = "50% 80%"
unfocus = "hide"
hysteresis = 0.7
restore_focus = true
[scratchpads.music]
animation = "fromBottom"
command = "spotify"
class = "Spotify"
size = "90% 85%"
multi = true
restore_focus = false
