#!/usr/bin/env lua5.4
---@version 5.4
-- /qompassai/hyprland/hypr/hypr.d/graphics/proton.lua
-- Qompass AI Hyprland 0.55+ Proton Graphics Lua Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-------------------------------------------------------
---@source https://github.com/jp7677/dxvk-nvapi/wiki
local home = os.getenv('HOME')
local cache_home = os.getenv('XDG_CACHE_HOME') or (os.getenv('HOME') .. '/.cache')
hl.env('DXVK_ENABLE_NVAPI', '1')
-- hl.env('DXVK_HDR' , 1)
hl.env('DXVK_NVAPI_ALLOW_OTHER_DRIVERS', '1')
-- hl.env('DXVK_NVAPI_DISABLE_ENTRYPOINTS', )
-- hl.env('DXVK_NVAPI_DRIVER_VERSION' , 58010)
-- hl.env('DXVK_NVAPI_DRS_SETTINGS' ,)
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE', 'on')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION', 'render_preset_latest')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION', 'render_preset_latest')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE', 'on')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_SR_MODE', 'quality')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE', 'on')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_RR_MODE', 'quality')
hl.env('DXVK_NVAPI_GPU_ARCH', 'AD100')
hl.env('DXVK_NVAPI_LOG_PATH', home .. '/.local/share/dxvk-nvapi')
hl.env('DXVK_NVAPI_VKREFLEX', '1')
hl.env('DXVK_NVAPI_VKREFLEX_ALLOW_FALLBACK_TO_OOB_FRAME_ID', '1')
hl.env('DXVK_NVAPI_VKREFLEX_ALLOW_FALLBACK_TO_PRESENT_FRAME_ID', '1')
hl.env('DXVK_NVAPI_VKREFLEX_ALLOW_FALLBACK_TO_SIMULATION_FRAME_ID', '1')
hl.env('DXVK_NVAPI_VKREFLEX_INJECT_PRESENT_FRAME_IDS', '0')
hl.env('DXVK_NVAPI_VKREFLEX_INJECT_SUBMIT_FRAME_IDS', '0')
hl.env('DXVK_NVAPI_VKREFLEX_LAYER_LOG_LEVEL', 'trace')
hl.env('DXVK_STATE_CACHE_PATH', home .. '/.local/share/dxvk-cache')
-- hl.env('ENABLE_HDR_WSI' , 1)
-- hl.env('ENABLE_VKBASALT', 1)
-- hl.env('PROTON_ENABLE_HDR' , 1)
hl.env('PROTON_ENABLE_NGX_UPDATER', '1')
hl.env('PROTON_ENABLE_NVAPI', '1')
hl.env('PROTON_ENABLE_WAYLAND', '1')
hl.env('PROTON_FORCE_LARGE_ADDRESS_AWARE', '1')
hl.env('PROTON_NO_ESYNC', '1')
hl.env('PROTON_USE_NTDLL_HAVE_THREAD', '1')
hl.env('PROTON_USE_WAYLAND', '1')
hl.env('DXVK_NVAPI_DRS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS', 'perf_to_9x')
hl.env('DXVK_NVAPI_ENABLE', '0')
hl.env('DXVK_NVAPI_VKREFLEX', '0')
--hl.env('VKD3D_CONFIG', 'dxr11,dxr')
